### PR TITLE
Optional file existence checks

### PR DESCRIPTION
**Pull request by mmatyas**
See #839 and #825.

### CODE REVIEW

**Comment by j8r** [comment]
I've checked both in my main PC and a slow one, I haven't seen any significant difference.
On my side this option has no use, does anyone can contradict me?
I'm all for better performance, but it will be counter-productive if this doesn't have any real-world effect.

**Comment by HVR88** [comment]
????  This makes all the difference. A few seconds startup versus multiple minutes.

**Comment by HVR88** [comment]
For me, yes, startup time is the same. As was explained in 839, there were two slowdowns which are not directly related. This merge resolves the slowdown caused by verifying ROM files only and won't have any effect on finding or loading media assets.

As 839 is still an open issue, I think it's perfectly valid to continue the discussion thread there along the path of improving the media lookup times. It was mentioned that disabling the media file checking might affect your startup times here: https://github.com/mmatyas/pegasus-frontend/issues/839#issuecomment-925139718

**Comment by j8r** [comment]
Yes of course. I was saying that because for me the first cold start is a lot longer than the second hot start, since the OS do filesystem caching, which speeds things up.

**Pull request merged**
