### PR TITLE
Add Epic Games provider

### PR DESCRIPTION
**Pull request by JMcKiern**
This PR adds an Epic Games provider to automatically populate games installed with Epic Games. Implements part of #671

I basically just copied the code for the Steam provider so feel free to make suggestions - I'm not too familiar with modern C++.

I still need to add some metadata parser but I'm struggling with using the info in the manifest file to retrieve the metadata. I will investigate when I get some time.

Perhaps it's worth cleaning this up and merging without the metadata provider? Let me know.

### CODE REVIEW

**Comment by mmatyas** [comment]
Nice work! Yeah, I'm okay with a game-only initial implementation, we can add the details later. Let me know when it's ready for review.

Some notes:
- You can use `/` for paths
- You can use JSON parsing for the item files
- This will probably pick up Unreal Engine and its installed plugins too, but it's OK for now

**Comment by mmatyas** [comment]
Do you plan to continue working on this? I could try to finish it.

**Comment by JMcKiern** [comment]
Sorry, been busy with other things. I probably won't get around to this any time soon so feel free to finish it if you'd like to.

**Comment by JMcKiern** [comment]
Im realistically not going to finish this so I will close

**Comment by innateessence** [comment]
Would love to see this finished and implemented

**Comment by innateessence** [comment]
@mmatyas Any chance you'll pick this up?

**Comment by mmatyas** [comment]
I'd like to add this feature, yes, but I'm not actively using Windows + Epic Store, so not sure when I'll get to it. (My current focus is the Qt6 port.) If anyone wants to work on this, feel free to open a PR.

**Comment by innateessence** [comment]
Would love to see this implemented for Linux : )

**Pull request closed without merging**
