### PR TITLE
Use flatpak spawn dbus send inside flatpak

### PR DESCRIPTION
**Pull request by j8r**
Fixes https://github.com/flathub/org.pegasus_frontend.Pegasus/issues/8.

In fact, related to https://github.com/mmatyas/pegasus-frontend/blob/master/src/backend/ProcessLauncher.cpp#L128

### CODE REVIEW

**Comment by j8r** [comment]
It will be the good opportunity to tag a new release after this merge, then use it in https://github.com/flathub/org.pegasus_frontend.Pegasus

**Comment by mmatyas** [comment]
Thanks!

**Comment by j8r** [comment]
Any planned release now that #873 is merged?

**Comment by mmatyas** [comment]
Oh, I did issue a new build after it got merged, but I might have forget to put the fix on the branch. One sec!

**Comment by mmatyas** [comment]
Ok, I pushed a new build, it should now contain the dbus fix after an update.

**Comment by j8r** [comment]
By release, I meant `alpha_16` , in order to have a new Flatpak version with the dbus fix.

**Comment by mmatyas** [comment]
There haven't been too many changes to release an Alpha 16, but that's not a requirement either: it is possible to publish a new build manually too for the same major version. Did a quick `flatpak update` last night, and I've got the updated version in about a minute after the build.

**Comment by j8r** [comment]
ha right, I got it, the shutdown and reboot works, but there is no sleep button.
In Flathub and the repository it is said it is the alpha15, so it is not really the case then?

I think it would be better to have more regular updates for the Flatpak, in order to have features quicker and test them before releases, especially Pegasus being still an alpha.

**Comment by mmatyas** [comment]
I suppose the site just shows whatever is written in the app's metadata file, probably won't show you the exact commit and such.

I agree, but that is exactly the opposite of Flathub's policy (https://github.com/flathub/flathub/wiki/App-Requirements#stable-releases-reproducible-builds). I think Flatpak-specific patches are probably fine though, which is why I added the Dbus fix.

**Comment by j8r** [comment]
As done on others flatpaks, a CRON can be setup to update regularly and automatically the according tags/commits in the files in the org.pegasus_frontend.Pegasus.yml file. I've done this for several projects.

**Comment by j8r** [comment]
As I and others have done on others flatpaks, a CRON can be set-up to update regularly and automatically the according tags/commits in the org.pegasus_frontend.Pegasus.yml file, that will then trigger a new build.

**Comment by j8r** [comment]
Thanks! As others  and I have done on others flatpaks, a CRON can be set-up to update regularly and automatically the according tags/commits in the org.pegasus_frontend.Pegasus.yml file, that will then trigger a new build.

**Comment by j8r** [comment]
If you're ok, I can do the same as https://github.com/flathub/org.duckstation.DuckStation/blob/master/.github/workflows/nightly.yml, using the `continuous` tag instead of `latest`.

**Comment by mmatyas** [comment]
The problem is, I cannot guarantee that the latest versions will always work, and from time to time they may also break features people depend on. According to what I linked above, this is exactly the kind of thing Flathub tries to avoid, for every app, explicitly mentioning _development snapshots_, such as nightlies. I understand many project don't really mind that, different people have different expectations, or it just doesn't make too much sense, but I'm not sure if we should go directly against an app submission guideline like that. Would you happen to know anyone from the Flathub team? I'd be nice to ask them for a clear statement about what is okay on the site and what is the level of stability that still fits into their idea.

**Comment by j8r** [comment]
Lots of app publish nightlies (look at https://github.com/flathub for recently updated applications), like emulators, which are in development. What can be considered stable? Application that have no releases and/or still in alpha can only submit builds at a given development state.

When I submitted the Flycast and DuckStation applications, which have no releases, the developers didn't point to me to this stable guideline. I think people prefer to have an "unstable" application, than having nothing at all.

I this very case, an alpha15.0.1 could have been created to bring the `dbus-send` fix, and a `alpha15.1` to add the `sleep` feature - I guess.

That's too bad we can't install easily a particular version with flatpak.

**Comment by mmatyas** [comment]
> What can be considered stable?

Indeed! It's hard to decide what the team counts as *stable*, when Flathub is full of unstable apps. Which is why an official statement would be nice.

Anyway, if you can port the workflow file to Pegasus, I guess I'm not against merging it. We'll see how it goes.

**Comment by j8r** [comment]
Otherwise, a nice balance, which is also done by DuckStation, is to have a rolling tag for "stable enough" points. They use a `preview`, which is quite regularly updated (~weekly), along with a `latest`, which is less updated (~monthly).

So, when one consider the state of master stable enough, but not worth a release, the HEAD of the preview tag can be moved up.

**Pull request merged**
